### ISSUE TITLE
实现离线下载

### ISSUE THREAD

**Issue by Ronaldoshuang** [ShouChenICU/FastSend#1]
发送者可以发送文件完毕，不用点确定，接收者直接就下载了呢？
![image](https://github.com/user-attachments/assets/bc3d9345-c558-4136-a206-21375cdde552)

**Comment by ShouChenICU** [comment]
点开右上角头像，勾选发送方自动确认即可。
加这个选项是为了防止被恶意随机输入取件码的人获取到文件

**Comment by Ronaldoshuang** [comment]
OK，了解
