### ISSUE TITLE
为什么手机浏览器打开无法传输？

### ISSUE THREAD

**Issue by wannianma** [ShouChenICU/FastSend#2]
刚开始是这样子
![image](https://github.com/user-attachments/assets/615659b7-1dcc-4cd6-9ded-8710b3acb3af)
过了会就会报服务异常
![image](https://github.com/user-attachments/assets/7fa7356e-6120-441e-872d-32492c113b4e)
感觉这个页面最大的应用场景还是手机和PC之间的文件互传，希望作者可以修复解决。

**Comment by ShouChenICU** [comment]
有开代理吗，关掉代理试试

因为是点对点直连，这个比较依赖网络环境，理论上局域网成功率最高，不是局域网的话建议关掉代理再用，再不行就换网络再试，有时候是运营商在干扰，可能过一会就好了

**Comment by BeanPlus** [comment]
直到现在还是存在这个问题，研究到现在，我把这个问题解决了，但手机移动网络和电脑传输，又会显示服务器超时，而手机在同一网段下是没有问题的。也就是局域网没问题，到了不同网络总是各种问题。
