### ISSUE TITLE
能支持命令行上传下载就更方便了

### ISSUE THREAD

**Issue by dissipator** [ShouChenICU/FastSend#3]
能支持命令行上传下载就更方便了

**Comment by Dragon1573** [comment]
这个项目不是文件暂存托管平台，用户双方是需要即时建立 P2P 连接的，个人想不到需要借助命令行 API 的使用场景。

是否可以说明一下你的命令行文件传输需求场景？不确定 **ShouChenICU** 会不会愿意加这个。

**Comment by jxyk2007** [comment]
> 这个项目不是文件暂存托管平台，用户双方是需要即时建立 P2P 连接的，个人想不到需要借助命令行 API 的使用场景。
> 
> 是否可以说明一下你的命令行文件传输需求场景？不确定 **ShouChenICU** 会不会愿意加这个。

pcdn用的到

**Comment by Dragon1573** [comment]
> 不确定 **ShouChenICU** 会不会愿意加这个。

重新回来翻了一下，按照目前 FastSend 的项目架构设计，传统 RESTful / GraphQL 命令行（比如 `curl`）上传/下载文件是不可能实现的。

不过可以考虑基于 FastSend 另行实现一个兼容 FastSend P2P 协议的专用 CLI ，我们目前暂无此意愿。
