### ISSUE TITLE
如何修改ip和端口号，重新部署呢

### ISSUE THREAD

**Issue by wuxiaolianggit** [ShouChenICU/FastSend#5]
您好，大佬，如何修改ip和端口号，重新部署呢 @ShouChenICU

**Comment by ShouChenICU** [comment]
端口号默认是`3000`，可以设置`PORT`环境变量修改，`IP`就是你部署的服务器的IP，建议用域名配置`HTTPS`访问

**Comment by wuxiaolianggit** [comment]
好的，了解，多谢大佬解答。还有我的页面出现*警告：您的浏览器不支持现代文件访问API，无法使用`目录同步`以及`发送目录`功能，同时接收文件限制1GB。，请大佬一般什么浏览器才可以支持全部功能呢 @ShouChenICU

**Comment by Dragon1573** [comment]
> 好的，了解，多谢大佬解答。还有我的页面出现 `*警告：您的浏览器不支持现代文件访问API，无法使用 目录同步 以及 发送目录 功能` ，同时接收文件限制1GB。
>
> 请大佬一般什么浏览器才可以支持全部功能呢？

一般是最新版本的 **Google Chrome** / **Microsoft Chromium Edge** / **Mozilla Firefox** 会支持，国产浏览器不保证其 Chromium / IE 内核能够支持。

我用 **Microsoft Edge 版本 131.0.2903.112 (正式版本) (64 位)** ，不会出现上述问题。

![image](https://github.com/user-attachments/assets/4a7408bd-f37a-420e-83f5-be982fb70eb2)

**Comment by wuxiaolianggit** [comment]
好的，了解，感谢大佬得到回复 @Dragon1573

**Comment by wuxiaolianggit** [comment]
我看了一下自己使用的浏览器，您的是一样的，但是出现上诉问题，不能传输目录文件 @Dragon1573

**Comment by Dragon1573** [comment]
> 我看了一下自己使用的浏览器，您的是一样的，但是出现上诉问题，不能传输目录文件

给出录屏或 _Edge DevTools_ 开发人员工具日志证明。

**Comment by Dragon1573** [comment]
> 我看了一下自己使用的浏览器，您的是一样的，但是出现上诉问题，不能传输目录文件

> [!IMPORTANT]
>
> 安全上下文: 此项功能仅在一些 [支持的浏览器](https://developer.mozilla.org/zh-CN/docs/Web/API/File_System_API#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7) 的 [安全上下文](https://developer.mozilla.org/zh-CN/docs/Web/Security/Secure_Contexts) （HTTPS）中可用。
>
> _原文发布于 [文件系统 API | MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/File_System_API#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7)_

[官站](https://fastsend.ing/zh) 服务配置了来自 **Google Trust Service** 签发的 站点 SSL 证书，所以能够正常使用此功能。

如果没有条件申请生产环境级证书，可以考虑借助 [`mkcert`](https://github.com/FiloSottile/mkcert) 创建用于本地开发环境的自签名证书，将你的 FastSend 站点副本切换为 HTTPS 上下文模式以启用 _文件系统 API_ 。

**Comment by wuxiaolianggit** [comment]
好的，了解，很感谢大佬耐心回复 @Dragon1573

**Comment by Dragon1573** [comment]
> 您好，大佬，如何修改ip和端口号，重新部署呢？

> [!TIP]
>
> 参见 https://github.com/ShouChenICU/FastSend/issues/9#issuecomment-2562353775 ，其中提及了启用 HTTPS 模式需要的环境变量。
