### ISSUE TITLE
在群辉里部署docker后，提示*警告：您的浏览器不支持现代文件访问API，无法使用`目录同步`以及`发送目录`功能，同时接收文件限制1GB。

### ISSUE THREAD

**Issue by leigeuo** [ShouChenICU/FastSend#6]
1、在群辉里部署这个docker：https://registry.hub.docker.com/r/918178/fastsend/
因为这个好像是更新版本最新的
2、群辉是家里的内网，将端口映射到公网
3、在公司访问网页，出现该提示，且确实没法接收文件夹
![Snipaste_2024-12-25_16-02-27](https://github.com/user-attachments/assets/53b7b530-a340-44a2-9674-3e5d226ee3e6)

**Comment by Dragon1573** [comment]
Duplicate of #5 

- See https://github.com/ShouChenICU/FastSend/issues/5#issuecomment-2561649995
