### ISSUE TITLE
https 配置支持

### ISSUE THREAD

**Issue by zhouhailin** [ShouChenICU/FastSend#9]
线上部署，是否可以增加一个 https 配置模板和说明

**Comment by Dragon1573** [comment]
参考 [Deployment · Get Started with Nuxt](https://nuxt.com/docs/getting-started/deployment#entry-point) 。

> [!TIP]
>
> 它遵守以下运行时环境变量：
>
> - 监听端口： `NITRO_PORT` 或 `PORT` (默认为 `3000`)
> - 监听主机： `NITRO_HOST` 或 `HOST` (默认为 `'0.0.0.0'` ，即监听所有主机)
> - SSL 证书和私钥： `NITRO_SSL_CERT` 和 `NITRO_SSL_KEY` - 如果两者同时存在，这会使服务器以 HTTPS 模式启动。在大多数场景下，这不应该在测试场景之外的情况下使用， _Nitro_ 服务器应该运行在 _Nginx_ 或 _Cloudflare_ 之类的反向代理之后，由这些反向代理提供 SSL 服务。
